// <auto-generated />
namespace LinkDev.VehicleLicense.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addRequstStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRequstStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202207241507466_addRequstStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
